FROM golang:1.20 AS backend

# dbServerLocation.txt: the text file that includes the location of database server
WORKDIR /lol_dict
COPY dbServerLocation.txt ./

# copy frontend files that are needed in backend files
WORKDIR /lol_dict/frontend
COPY frontend/ .

# download go modules
WORKDIR /lol_dict/backend
COPY ./backend/go.mod ./backend/go.sum ./
RUN go mod download
# Copy all files in ./backend and its sub directory
COPY ./backend/ ./

# run test
CMD [ "go", "test", "-v" ]