name: learn-github-actions
on:
  push:
    branches:
      - browserify
jobs:
  test-frontend-and-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checkout source code
      - name: check if env variables are correctly set 
        run: |
          cd backend
          source .env
          if [ "$MODE" != "dev_localhost" && "$MODE" != "dev_container" ]; then exit 1; fi
      - name: run test on docker-compose
        run: |
          docker-compose -f ./backend-test.yml up --build --abort-on-container-exit
          docker-compose -f ./frontend-test.yml up --build --abort-on-container-exit
        working-directory: ./