name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        run: ls -al
      - name: install node
        uses: actions/setup-node@v4
      - name: npm install
        run: npm install
      - name: run jest
        run: stefanoeb/jest-action@latest
    